### ISSUE TITLE
PDF creation broken after configuration

### ISSUE THREAD

**Issue by EugenZimmermann** [thawn/ttmp32gme#32] opened 2020-01-09 21:45 UTC
Hi,

I think I broke my configuration for PDF printing after setting the number of tracks to 36 (instead of 24). For 30 it was showing an additional streched row, however, changing to 36 broke the whole process and the terminal is stating:

```
Use of uninitialized value $oid in concatenation (.) or string at TTMp32Gme/TttoolHandler.pm line 273.
Use of uninitialized value $oid in concatenation (.) or string at TTMp32Gme/TttoolHandler.pm line 275.
C:\Users\eugen\AppData\Local\Temp\par-657567656e\cache-6a789dcfc1f65d227392c3caf2d9983f1b360a37\inc\lib\tttool.exe --dpi 1200 --pixel-size 3  --code-dim 24 oid-code
Missing: RANGE

Usage: tttool.exe oid-code [--raw] RANGE
  creates PNG files for each given code(s)

Available options:
  --raw                    take the given codes as "raw codes" (rarely needed)
  RANGE                    OID range, for example e.g. 1,3,1000-1085.
  -h,--help                Show this help text

Uses oid-<code>.png as the file name.

Use the global options to configure size, resolution and blackness of the code
(see ./tttool --help).

Note that it used to work to call "tttool oid-code foo.yaml". Please use "tttool
oid-codes" for that now.
[ERROR]
unhandled callback exception on event (/print, AnyEvent::HTTPD=HASH(0x915b3a8), AnyEvent::HTTPD::Request=HASH(0x956e088)): Could not create oid file:  at TTMp32Gme/TttoolHandler.pm line 275.
```

This is now thrown every time I try to print something and the print screen does not open. I guess this might be fixed by changing the specific configuration, but I can't even access the corresponding page and I couldn't find a corresponding configuration file within the application folder/library.

Cheers and thx,
Eugen

**Comment by thawn** [comment] 2020-01-21 08:23
Hi,
Thanks a lot for taking the time to report this bug.
Which version of ttmp32gme are you using? Try running the latest version 0.3.3. Maybe that fixes your problem.

If it doesn't, there are two possible workarounds:
1) delete the library folder (check the configuration page for the path to the library) However, this means that you will need to re-upload everything
2) open config.sqlite with a sqlite editor and change the value of print_max_track_controls to 24

**Comment by EugenZimmermann** [comment] 2020-01-21 19:26
Hi,

thank you. I guess changing the settings in the config.sqlite would have fixed it. Luckily it got solved on its own be rebooting the system. After reboot the print page was opening again and even showed the last configuration (36 tracks) properly. Are there any temporary files created which can cause this behavior? Anyway, thanks for your support :).

Cheers,
Eugen

**Comment by thawn** [comment] 2020-01-22 07:53
that is indeed a weird behavior. Maybe something got messed up with your javascript session. I'll try to reproduce this.

**Comment by thawn** [comment] 2020-04-18 09:32
Could not reproduce the behavior. Closing issue.

**Closed by thawn** 2020-04-18 09:32 UTC
