### ISSUE TITLE
Error starting ttmp32gme.exe on user directory using non-ASCII characters (encoding problem?)

### ISSUE THREAD

**Issue by antonhoess** [thawn/ttmp32gme#41] opened 2020-12-12 08:00 UTC
Hello,

when running ttmp32gme.exe from command line, I get this error:
`DBI connect('dbname=C:\Users\Anton H÷▀\AppData\Roaming\ttmp32gme\config.sqlite','',...) failed: unable to open database file at script/ttmp32gme.pl line 83.`

The correct path is `C:\Users\Anton Höß\AppData\Roaming\ttmp32gme\config.sqlite` and this file also exists.

I made following attempts without success (only for this tries I created the folder C:\tmp and copied config.sqlite into it):
- Setting the HOME environment variable using `set HOME=C:\tmp` 
- Using the option `ttmp32gme.exe -c C:\tmp` (and copying the config file `config.sqlite` from C:\Users\Anton Höß\AppData\Roaming\ttmp32gme to C:\tmp)

Then I tried to call the tool using just `ttmp32gme.exe` with my administrator account, since I think, the umlauts (enocding) are the reason the call of `ttmp32gme.exe` (without parameters) is not working and the administrator accound doen't have any umlaut in its path. And success, the browser window apeared and I could work with it.

I was anyway surprised, that as a normal user it didn't work using the `-c` option. Checking the code `src/ttmp32gme.pl` it seems to me that the variable `configdir` never gets used/evaluated? Therefore I can't work using `-c C:\tmp`.

Am I wrong and if so, where does this argument gets evaluated? And where does `checkConfigFile()` come from, which sets the variable `$configFile`?

I hope, you can help me and fix this, if it's an bug and thanks for helping!

Best,
Anton

**Comment by derpicknicker1** [comment] 2021-01-22 08:51
I have the same problem on one of my machines:
```
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at Music/Tag.pm line 1066, <DATA> line 1.
DBI connect('dbname=C:\Users\FlorianSch³tte\AppData\Roaming\ttmp32gme\config.sqlite','',...) failed: unable to open database file at script/ttmp32gme.pl line 83.
Could not open config file.
```

**Comment by thawn** [comment] 2021-01-22 09:59
I can confirm that ttmp32gme does not work on windows with umlauts (or other non-ASCII characters) in the username.

I can also confirm that setting a custom path to the config file does not work.

I am putting these two bugs on my todo list for the next release. I will most likely remove the command line option once ttmp32gme works with all user names, since this makes testing and debugging easier and more reliable.

**Comment by schirinowski** [comment] 2021-02-03 20:00
Same here, carrying an 'ö' in the user name. Thanks for considering this for the next release.

My workaround so far:
1. Hold down the shift key and right-click the executable
2. Choose "run as different user"
3. Enter the credentials of a non-umlauts user account on your machine (it needs to have a password).

This makes it run without having to log into another user account.

**Comment by thawn** [comment] 2021-02-15 00:39
The bug should be fixed in the latest release v0.3.4. I would be very grateful for feedback if this works for you.

**Closed by thawn** 2021-02-15 00:39 UTC
Labels: bug

**Comment by antonhoess** [comment] 2021-02-15 10:49
Unfortunately I had to chance my user's path (now it's `C:\Users\anton` to a path without spaces or special characters for another reason, so I cannot test it anymore, but hopefully one of the ofters that had the same problem. But I can say, that the new version now ran perfectly from my Downloads folter.

**Comment by thawn** [comment] 2021-02-15 11:24
@antonhoess thank you very much for your feedback! I am glad that the software works for you now. 

Actually, I am not surprised, that you had problems with that user folder name. Unfortunately, a lot of software (like ttmp32gme ;-) ) is never thoroughly tested with unicode characters in paths and therefore this frequently causes errors.

**Comment by schirinowski** [comment] 2021-02-19 16:42
@thawn, eggsellent work! ttmp32gme now starts without any hiccups. 👍 

What I saw is that the standard _ttmp32gme library path_ is rendered wrong on the config page http://127.0.0.1:10020/config
I checked, the path is correctly used as `C:\Users\ömlöut-öser\AppData\Roaming\ttmp32gme\`, but the configuration page says
`C:\Users\�ml�ut-�ser\AppData\Roaming\ttmp32gme\`. I assume the path is internally handled correctly, but the web server output codepage is not assigned correctly.

I checked this in the 64 bit versions of both Firefox (85.0.2) and MS Edge (88.0.705.68) on Windows 10.

**Comment by thawn** [comment] 2021-02-19 17:16
@schirinowski thank you very much for the feedback! You are right, the path on the config page is rendered wrong. This is because the web browser uses the wrong codepage. I will try to fix this in a separate issue

**Comment by schirinowski** [comment] 2021-02-19 18:16
@thawn, does make sense. 😁👍
Anyway, I'm so happy I can delete my "tiptoi" user account. Thanks for fixing _this_ issue.
