### ISSUE TITLE
Mac 64 bit version

### ISSUE THREAD

**Issue by jens2305** [thawn/ttmp32gme#30] opened 2019-11-11 14:46 UTC
Thanks for this awesome tool. Is there a chance to get a 64 bit MacOS version, since macOS Catalina is no longer working with 32 bit.

**Comment by thawn** [comment] 2019-11-11 20:01
@jens2305 I will look into it. Meanwhile, you may be able to get the docker version to work. I have only tested the docker version under linux but mac OS should work just as well. Let me know how that goes :)

**Comment by m313** [comment] 2019-11-24 21:45
Hi!
I'm also running OSX Catalina without 32bit support, so I tried the Docker version, downloading  install.sh and ttmp32gme as described. However, it seems the tiptoi is mounted (I can see it in Finder) but not recognized. I have tried specifying the path to tiptoi:
```
$ ttmp32gme start /Volumes/tiptoi/
/usr/local/bin/ttmp32gme: line 13: /media/${'USER'}/tiptoi/tiptoi.ico: bad substitution
a355688fc142e328f44b46633aa836b3b897919bd7414a61f9ee953089ce12dc
Successfully started ttmp32gme open http://localhost:8080 in your browser to continue.
```
However, I still don't see a button with "Copy selected to TipToi" on the Library page.

Is it possible to manually copy GME files to the tiptoi? On the Library page, I see the following Path: 
`/var/lib/ttmp32gme/library/Sing_mit_mir_Kinderlieder`
However, when I try to navigate there, it seems the directory `/var/lib/ttmp32gme` does not exist on my machine.

Also, I'm not sure if the GME files were properly created. After clicking on "Create GME" on the Library page, the fields for "GME file:" and "Path:" were populated, but there was no confirmation message.

Any help would be appreciated :) Thanks!

**Comment by thawn** [comment] 2019-12-15 16:21
@m313 I will look into it but I cannot make any promises as to when I'll be able to fix this.

**Comment by thawn** [comment] 2020-01-05 15:39
fixed in version 0.3.2. I would be very happy about feedback if it works as intended.

**Closed** 2020-01-05 15:39 UTC

**Comment by jens2305** [comment] 2020-01-05 19:34
Works like a charm. Thanks for the update.
Jens

**Comment by thawn** [comment] 2020-01-07 08:07
thanks for the feedback :-)
