### ISSUE TITLE
Upload process is not intuitive

### ISSUE THREAD

**Issue by jasonhildebrand** [thawn/ttmp32gme#25] opened 2019-05-31 15:24 UTC
I have tried uploading various files, but it spins and spins and never completes.  I have tried both OGG and MP3 files.  Nothing shows up in the library.

I am using the docker image under linux.  I am familiar with docker/linux.  Are there any log files inside the docker container that I can check to see what the issue might be?

**Comment by jasonhildebrand** [comment] 2019-06-01 02:34
I figured it out.  The spinning images beside the tracks gave me the impression that the files were uploading.  It was not clear to me that I needed to click "Add Album to Library" in order to proceed.

I would suggest the following UI changes to make it more intuitive for first-time users:
* remove the spinning image beside each track
* move the "Add Album to Library" button to below the box.  Make it greyed out initially, until at least one track has been added.
* Change the instructions to: Add album/audiobook files by dragging and dropping them into the box below or by clicking on "Select files".  When you have added all tracks for one album/audiobook, click "Add Album to Library" button.  Add only one album/audiobook at a time (the album information will be extracted from the id3 tag of the first file that is uploaded).

**Comment by thawn** [comment] 2019-06-01 11:36
@jasonhildebrand Thank you very much for filing this issue and posting your workaround.

The spinning image next to each track should not be there (or rather it should disappear very quickly). I just tested this on my system and was able to reproduce the error with a docker image but not with the mac executable version.

The first and the last point of your suggestions seem like a good idea - I will look into that as soon as I find the time.

Moving the button to the bottom may be counterproductive because it may be easily overlooked on smaller screens. Also, this is not something easily done because the whole upload box is a provided using a javascript library.

**Comment by thawn** [comment] 2019-06-01 14:39
This should be fixed in the latest docker release

**Closed by thawn** 2019-06-01 14:39 UTC

**Comment by jasonhildebrand** [comment] 2019-06-01 14:53
Wow, that was amazingly quick!  I pulled the latest docker image and can confirm the improvement.
Thanks!
