### ISSUE TITLE
Problem with "Library" page

### ISSUE THREAD

**Issue by nvern** [thawn/ttmp32gme#10] opened 2017-04-18 13:13 UTC
Hi, 

when I try to add the uploaded mp3's to the Library, I get this error:

[MSG] using tttool: C:\Users\myuser\AppData\Local\Temp\par-6e766572\cache-8f1304b3
f7e188adb49363ef0e48ad20dae87431\inc\lib\tttool.exe
copying albums to library
unhandled callback exception on event (/, AnyEvent::HTTPD=HASH(0x8239ff8), AnyEv
ent::HTTPD::Request=HASH(0x8080748)): Can't call method "get_frame" on an undefi
ned value at TTMp32Gme/LibraryHandler.pm line 212.

OS: Win7, Browser: FF/Chrome

**Comment by thawn** [comment] 2017-04-18 14:06
Hi,

this is a problem with reading the mp3 metadata. Which version of 
ttmp32gme are you using? If you are using a version older than at least 
v 0.2.0, please update and try again. If you are already using v0.2.0, 
could you please send me one of the mp3s so that I can try to reproduce 
the issue?

Cheers

Till

**Comment by nvern** [comment] 2017-04-21 09:01
Hi,

I'm using v0.2.0.
Here is a test-mp3.

Cheers
Robert
[mp3.zip](https://github.com/thawn/ttmp32gme/files/946528/mp3.zip)

**Comment by thawn** [comment] 2017-06-04 15:02
Hi Robert,

thanks for the mp3. The problem is now fixed in version 0.2.1

**Closed by thawn** 2017-06-04 15:02 UTC
